// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DoxyTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "DoxyTools.c076aebc-f08b-46e6-a2c1-46dfe21f44fe";
        public const string Name = "DoxyTools";
        public const string Description = @"Using Doxygen from the comfort of Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
