// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DoxyTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DoxyToolsString = "3be68a4e-444c-4cc1-b6a4-1e7c24dfd3d0";
        public static Guid DoxyTools = new Guid(DoxyToolsString);

        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProjectRightClick = 0x0001;
        public const int ExtensionsTab = 0x1020;
        public const int GenerateDocs = 0x0100;
        public const int ViewDocs = 0x0101;
        public const int GenerateAllDocs = 0x1021;
        public const int IDM_VS_MENU_EXTENSIONS = 0x0091;
    }
}